name: giuseppe
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  flutter_vision: ^1.1.4
  image_picker: ^1.1.2
  pdf: ^3.11.1
  printing: ^5.13.4
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  provider: ^6.1.2
  firebase_storage: ^12.3.6
  intl: ^0.20.1
  lottie: ^3.1.3
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  shared_preferences: ^2.3.3
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/users/
    - assets/models/
    - assets/fonts/
    - assets/lottiefiles/
